require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety
  - rubocop-minitest

AllCops:
  SuggestExtensions: false
  NewCops: enable

Gemspec/RequireMFA:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false
