plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety
  - rubocop-minitest

AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 4.0

Gemspec/RequireMFA:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - lib/rama.rb

Style/Documentation:
  Enabled: false
